<?php
namespace RecipeSuggester\Parser\Ingredient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-14 at 02:51:14.
 */
class CsvTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Csv
     */
    protected $parser;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->parser = new Csv;
    }

    /**
     * Asserts that an exception is thrown when given an invalid format
     *
     * @covers RecipeSuggester\Parser\Ingredient\Csv::parse
     * @expectedException \RecipeSuggester\Parser\InvalidFormatException
     */
    public function testParseInvalidFormat()
    {
        // JSON should not be allowed in a CSV!
        $this->parser->parse("{'this is json': true}");
    }

    /**
     * Asserts that an exception is thrown when given an invalid format
     *
     * @covers RecipeSuggester\Parser\Ingredient\Csv::parse
     * @expectedException \RecipeSuggester\Parser\InvalidFormatException
     */
    public function testParseInvalidQuantity()
    {
        // JSON should not be allowed in a CSV!
        $this->parser->parse('bread,four,slices,12/12/2014');
    }

    /**
     * Asserts that an exception is thrown when given an invalid format
     *
     * @covers RecipeSuggester\Parser\Ingredient\Csv::parse
     * @expectedException \RecipeSuggester\Parser\InvalidFormatException
     */
    public function testParseInvalidUnit()
    {
        // JSON should not be allowed in a CSV!
        $this->parser->parse('bread,4,slice,12/12/2014');
    }

    /**
     * Asserts that an exception is thrown when given an invalid format
     *
     * @covers RecipeSuggester\Parser\Ingredient\Csv::parse
     * @expectedException \RecipeSuggester\Parser\InvalidFormatException
     */
    public function testParseInvalidDate()
    {
        // JSON should not be allowed in a CSV!
        $this->parser->parse('bread,4,slices,2014-04-04');
    }

    /**
     * @covers RecipeSuggester\Parser\Ingredient\Csv::parse
     */
    public function testParseValidFormat()
    {
        $ingredients = $this->parser->parse("bread,4,slices,04/04/2014\ncheese,2,slices,04/04/2014");

        $this->assertEquals(2, sizeof($ingredients), 'Should parse two ingredients');
        $this->assertEquals('bread', $ingredients[0]->getItem());
    }
}
