<?php
namespace RecipeSuggester\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-14 at 02:36:18.
 */
class PantryTest extends \PHPUnit_Framework_TestCase
{
    protected $pantry;

    public function setUp()
    {
        $this->pantry = new Pantry(array(
            new Ingredient('bread', 10, 'slices'),
            new Ingredient('cheese', 10, 'slices'),
            new Ingredient('salad', 500, 'grams')
        ));
    }


    public function hasIngredientsForRecipeProvider()
    {
        return array(
            array(
                'Cheese sandwich',
                array(
                    new Ingredient('bread', 2, 'slices'),
                    new Ingredient('cheese', 2, 'slices')
                ),
                true
            ),
            array(
                'Salad sandwich',
                array(
                    new Ingredient('bread', 2, 'slices'),
                    new Ingredient('salad', 200, 'grams')
                ),
                true
            ),
            array(
                'Peanut butter sandwich',
                array(
                    new Ingredient('bread', 2, 'slices'),
                    new Ingredient('peanut butter', 100, 'grams')
                ),
                false
            )
        );
    }


    /**
     * @covers RecipeSuggester\Model\Pantry::hasIngredientsForRecipe
     * @dataProvider hasIngredientsForRecipeProvider
     */
    public function testHasIngredientsForRecipe($name, array $ingredients, $expectedResult)
    {
        $this->assertEquals($expectedResult,
            $this->pantry->hasIngredientsForRecipe(
                new Recipe($name, $ingredients)
            )
        );
    }
}
