<?php
namespace RecipeSuggester\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-14 at 01:30:01.
 */
class RecipeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers RecipeSuggester\Model\Recipe::canUseIngredient
     * @todo   Implement testCanUseIngredient().
     */
    public function testCanUseIngredient()
    {
        $recipe = new Recipe('Cheese sandwich', array(
            new Ingredient('bread', 2, 'slices'),
            new Ingredient('cheese', 2, 'slices')
        ));

        $this->assertTrue(
            $recipe->canUseIngredient(new Ingredient('bread', 10, 'slices'))
        );
        $this->assertTrue(
            $recipe->canUseIngredient(new Ingredient('bread', 2, 'slices'))
        );
        $this->assertFalse(
            $recipe->canUseIngredient(new Ingredient('bread', 1, 'slices'))
        );
        $this->assertFalse(
            $recipe->canUseIngredient(new Ingredient('bread', 500, 'grams'))
        );
        $this->assertTrue(
            $recipe->canUseIngredient(new Ingredient('cheese', 50, 'slices'))
        );
        $this->assertFalse(
            $recipe->canUseIngredient(new Ingredient('cheese', 500, 'grams'))
        );
        $this->assertFalse(
            $recipe->canUseIngredient(new Ingredient('brot', 50, 'slices'))
        );
        $this->assertFalse(
            $recipe->canUseIngredient(new Ingredient('bread', 10, 'slices', new \DateTime('yesterday')))
        );
    }
}
