<?php
namespace RecipeSuggester;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-14 at 03:43:03.
 */
class CliTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cli
     */
    protected $cli;

    /**
     *
     * @var Pimple
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = new \Pimple;
        $this->cli = new Cli($this->container);
    }

    /**
     * @covers RecipeSuggester\Cli::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
