<?php
namespace RecipeSuggester\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-14 at 01:30:01.
 */
class RecipeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Recipe
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Recipe;
    }

    /**
     * @covers RecipeSuggester\Model\Recipe::canUseIngredient
     * @todo   Implement testCanUseIngredient().
     */
    public function testCanUseIngredient()
    {
        $this->object->setIngredients(array(
            new Ingredient('bread', 2, 'slices'),
            new Ingredient('cheese', 2, 'slices')
        ));

        $this->assertTrue(
            $this->object->canUseIngredient(new Ingredient('bread', 10, 'slices'))
        );
        $this->assertTrue(
            $this->object->canUseIngredient(new Ingredient('bread', 2, 'slices'))
        );
        $this->assertFalse(
            $this->object->canUseIngredient(new Ingredient('bread', 1, 'slices'))
        );
        $this->assertFalse(
            $this->object->canUseIngredient(new Ingredient('bread', 500, 'grams'))
        );
        $this->assertTrue(
            $this->object->canUseIngredient(new Ingredient('cheese', 50, 'slices'))
        );
        $this->assertFalse(
            $this->object->canUseIngredient(new Ingredient('cheese', 500, 'grams'))
        );
        $this->assertFalse(
            $this->object->canUseIngredient(new Ingredient('brot', 50, 'slices'))
        );
    }
}
